/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateReplicaBody : Create Replica Body JSON



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReplicaBody {
    /// protocol to expose the replica over
    #[serde(rename = "share")]
    pub share: Share,
    /// size of the replica in bytes
    #[serde(rename = "size")]
    pub size: i64,
    /// thin provisioning
    #[serde(rename = "thin")]
    pub thin: bool,
}

impl CreateReplicaBody {
    /// Create Replica Body JSON
    pub fn new(share: Share, size: i64, thin: bool) -> CreateReplicaBody {
        CreateReplicaBody {
            share,
            size,
            thin,
        }
    }
}

/// protocol to expose the replica over
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Share {
    #[serde(rename = "false")]
    _False,
    #[serde(rename = "nvmf")]
    Nvmf,
    #[serde(rename = "iscsi")]
    Iscsi,
    #[serde(rename = "nbd")]
    Nbd,
}

