/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateVolumeBodyPolicyTopologyLabelledPoolTopology : pool topology



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVolumeBodyPolicyTopologyLabelledPoolTopology {
    /// inclusive labels
    #[serde(rename = "inclusion")]
    pub inclusion: Vec<String>,
}

impl CreateVolumeBodyPolicyTopologyLabelledPoolTopology {
    /// pool topology
    pub fn new(inclusion: Vec<String>) -> CreateVolumeBodyPolicyTopologyLabelledPoolTopology {
        CreateVolumeBodyPolicyTopologyLabelledPoolTopology {
            inclusion,
        }
    }
}


