/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateVolumeBody : Create Volume Body JSON



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVolumeBody {
    #[serde(rename = "policy")]
    pub policy: Box<crate::models::CreateVolumeBodyPolicy>,
    /// number of storage replicas
    #[serde(rename = "replicas")]
    pub replicas: i64,
    /// size of the volume in bytes
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "topology")]
    pub topology: Box<crate::models::CreateVolumeBodyTopology>,
}

impl CreateVolumeBody {
    /// Create Volume Body JSON
    pub fn new(policy: crate::models::CreateVolumeBodyPolicy, replicas: i64, size: i64, topology: crate::models::CreateVolumeBodyTopology) -> CreateVolumeBody {
        CreateVolumeBody {
            policy: Box::new(policy),
            replicas,
            size,
            topology: Box::new(topology),
        }
    }
}


