/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateVolumeBodyPolicyTopologyExplicit : volume topology, explicitly selected



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVolumeBodyPolicyTopologyExplicit {
    /// replicas can only be placed on these nodes
    #[serde(rename = "allowed_nodes")]
    pub allowed_nodes: Vec<String>,
    /// preferred nodes to place the replicas
    #[serde(rename = "preferred_nodes")]
    pub preferred_nodes: Vec<String>,
}

impl CreateVolumeBodyPolicyTopologyExplicit {
    /// volume topology, explicitly selected
    pub fn new(allowed_nodes: Vec<String>, preferred_nodes: Vec<String>) -> CreateVolumeBodyPolicyTopologyExplicit {
        CreateVolumeBodyPolicyTopologyExplicit {
            allowed_nodes,
            preferred_nodes,
        }
    }
}


