/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateVolumeBodyPolicyTopology : topology to choose a replacement replica for self healing  (overrides the initial creation topology)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVolumeBodyPolicyTopology {
    #[serde(rename = "explicit", skip_serializing_if = "Option::is_none")]
    pub explicit: Option<Box<crate::models::CreateVolumeBodyPolicyTopologyExplicit>>,
    #[serde(rename = "labelled", skip_serializing_if = "Option::is_none")]
    pub labelled: Option<Box<crate::models::CreateVolumeBodyPolicyTopologyLabelled>>,
}

impl CreateVolumeBodyPolicyTopology {
    /// topology to choose a replacement replica for self healing  (overrides the initial creation topology)
    pub fn new() -> CreateVolumeBodyPolicyTopology {
        CreateVolumeBodyPolicyTopology {
            explicit: None,
            labelled: None,
        }
    }
}


