/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateVolumeBodyPolicyTopologyLabelled : volume topology using labels



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVolumeBodyPolicyTopologyLabelled {
    #[serde(rename = "node_topology")]
    pub node_topology: Box<crate::models::CreateVolumeBodyPolicyTopologyLabelledNodeTopology>,
    #[serde(rename = "pool_topology")]
    pub pool_topology: Box<crate::models::CreateVolumeBodyPolicyTopologyLabelledPoolTopology>,
}

impl CreateVolumeBodyPolicyTopologyLabelled {
    /// volume topology using labels
    pub fn new(node_topology: crate::models::CreateVolumeBodyPolicyTopologyLabelledNodeTopology, pool_topology: crate::models::CreateVolumeBodyPolicyTopologyLabelledPoolTopology) -> CreateVolumeBodyPolicyTopologyLabelled {
        CreateVolumeBodyPolicyTopologyLabelled {
            node_topology: Box::new(node_topology),
            pool_topology: Box::new(pool_topology),
        }
    }
}


