/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateNexusBody : Create Nexus Body JSON



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateNexusBody {
    /// replica can be iscsi and nvmf remote targets or a local spdk bdev  (i.e. bdev:///name-of-the-bdev).   uris to the targets we connect to
    #[serde(rename = "children")]
    pub children: Vec<String>,
    /// size of the device in bytes
    #[serde(rename = "size")]
    pub size: i64,
}

impl CreateNexusBody {
    /// Create Nexus Body JSON
    pub fn new(children: Vec<String>, size: i64) -> CreateNexusBody {
        CreateNexusBody {
            children,
            size,
        }
    }
}


