/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreatePoolBody : Create Pool Body JSON



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePoolBody {
    /// disk device paths or URIs to be claimed by the pool
    #[serde(rename = "disks")]
    pub disks: Vec<String>,
}

impl CreatePoolBody {
    /// Create Pool Body JSON
    pub fn new(disks: Vec<String>) -> CreatePoolBody {
        CreatePoolBody {
            disks,
        }
    }
}


