/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JsonGeneric : Generic JSON value eg: { \"size\": 1024 }



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonGeneric {
    #[serde(rename = "inner")]
    pub inner: serde_json::Value,
}

impl JsonGeneric {
    /// Generic JSON value eg: { \"size\": 1024 }
    pub fn new(inner: serde_json::Value) -> JsonGeneric {
        JsonGeneric {
            inner,
        }
    }
}


