/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NexusChildren : Child information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NexusChildren {
    /// current rebuild progress (%)
    #[serde(rename = "rebuildProgress", skip_serializing_if = "Option::is_none")]
    pub rebuild_progress: Option<i32>,
    /// state of the child
    #[serde(rename = "state")]
    pub state: State,
    /// uri of the child device
    #[serde(rename = "uri")]
    pub uri: String,
}

impl NexusChildren {
    /// Child information
    pub fn new(state: State, uri: String) -> NexusChildren {
        NexusChildren {
            rebuild_progress: None,
            state,
            uri,
        }
    }
}

/// state of the child
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Online")]
    Online,
    #[serde(rename = "Degraded")]
    Degraded,
    #[serde(rename = "Faulted")]
    Faulted,
}

