/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Node : Node information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Node {
    /// grpc_endpoint of the mayastor instance
    #[serde(rename = "grpcEndpoint")]
    pub grpc_endpoint: String,
    /// id of the mayastor instance
    #[serde(rename = "id")]
    pub id: String,
    /// deemed state of the node
    #[serde(rename = "state")]
    pub state: State,
}

impl Node {
    /// Node information
    pub fn new(grpc_endpoint: String, id: String, state: State) -> Node {
        Node {
            grpc_endpoint,
            id,
            state,
        }
    }
}

/// deemed state of the node
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Online")]
    Online,
    #[serde(rename = "Offline")]
    Offline,
}

