/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Pool : Pool information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pool {
    /// size of the pool in bytes
    #[serde(rename = "capacity")]
    pub capacity: i64,
    /// absolute disk paths claimed by the pool
    #[serde(rename = "disks")]
    pub disks: Vec<String>,
    /// id of the pool
    #[serde(rename = "id")]
    pub id: String,
    /// id of the mayastor instance
    #[serde(rename = "node")]
    pub node: String,
    /// current state of the pool
    #[serde(rename = "state")]
    pub state: State,
    /// used bytes from the pool
    #[serde(rename = "used")]
    pub used: i64,
}

impl Pool {
    /// Pool information
    pub fn new(capacity: i64, disks: Vec<String>, id: String, node: String, state: State, used: i64) -> Pool {
        Pool {
            capacity,
            disks,
            id,
            node,
            state,
            used,
        }
    }
}

/// current state of the pool
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Online")]
    Online,
    #[serde(rename = "Degraded")]
    Degraded,
    #[serde(rename = "Faulted")]
    Faulted,
}

