/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Replica : Replica information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Replica {
    /// id of the mayastor instance
    #[serde(rename = "node")]
    pub node: String,
    /// id of the pool
    #[serde(rename = "pool")]
    pub pool: String,
    /// protocol used for exposing the replica
    #[serde(rename = "share")]
    pub share: Share,
    /// size of the replica in bytes
    #[serde(rename = "size")]
    pub size: i64,
    /// state of the replica
    #[serde(rename = "state")]
    pub state: State,
    /// thin provisioning
    #[serde(rename = "thin")]
    pub thin: bool,
    /// uri usable by nexus to access it
    #[serde(rename = "uri")]
    pub uri: String,
    /// uuid of the replica
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl Replica {
    /// Replica information
    pub fn new(node: String, pool: String, share: Share, size: i64, state: State, thin: bool, uri: String, uuid: String) -> Replica {
        Replica {
            node,
            pool,
            share,
            size,
            state,
            thin,
            uri,
            uuid,
        }
    }
}

/// protocol used for exposing the replica
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Share {
    #[serde(rename = "false")]
    _False,
    #[serde(rename = "nvmf")]
    Nvmf,
    #[serde(rename = "iscsi")]
    Iscsi,
    #[serde(rename = "nbd")]
    Nbd,
}
/// state of the replica
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "faulted")]
    Faulted,
}

