/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RestWatch : Watch Resource in the store



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestWatch {
    /// callback used to notify the watcher of a change
    #[serde(rename = "callback")]
    pub callback: String,
    /// id of the resource to watch on
    #[serde(rename = "resource")]
    pub resource: String,
}

impl RestWatch {
    /// Watch Resource in the store
    pub fn new(callback: String, resource: String) -> RestWatch {
        RestWatch {
            callback,
            resource,
        }
    }
}


