/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RestJsonError : Rest Json Error format



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestJsonError {
    /// detailed error information
    #[serde(rename = "details")]
    pub details: String,
    /// error kind
    #[serde(rename = "error")]
    pub error: Error,
}

impl RestJsonError {
    /// Rest Json Error format
    pub fn new(details: String, error: Error) -> RestJsonError {
        RestJsonError {
            details,
            error,
        }
    }
}

/// error kind
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "Timeout")]
    Timeout,
    #[serde(rename = "Deserialize")]
    Deserialize,
    #[serde(rename = "Internal")]
    Internal,
    #[serde(rename = "InvalidArgument")]
    InvalidArgument,
    #[serde(rename = "DeadlineExceeded")]
    DeadlineExceeded,
    #[serde(rename = "NotFound")]
    NotFound,
    #[serde(rename = "AlreadyExists")]
    AlreadyExists,
    #[serde(rename = "PermissionDenied")]
    PermissionDenied,
    #[serde(rename = "ResourceExhausted")]
    ResourceExhausted,
    #[serde(rename = "FailedPrecondition")]
    FailedPrecondition,
    #[serde(rename = "NotShared")]
    NotShared,
    #[serde(rename = "NotPublished")]
    NotPublished,
    #[serde(rename = "AlreadyPublished")]
    AlreadyPublished,
    #[serde(rename = "AlreadyShared")]
    AlreadyShared,
    #[serde(rename = "Aborted")]
    Aborted,
    #[serde(rename = "OutOfRange")]
    OutOfRange,
    #[serde(rename = "Unimplemented")]
    Unimplemented,
    #[serde(rename = "Unavailable")]
    Unavailable,
    #[serde(rename = "Unauthenticated")]
    Unauthenticated,
    #[serde(rename = "Unauthorized")]
    Unauthorized,
    #[serde(rename = "Conflict")]
    Conflict,
    #[serde(rename = "FailedPersist")]
    FailedPersist,
    #[serde(rename = "Deleting")]
    Deleting,
}

