/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SpecsOperation1 : Record of the operation in progress



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpecsOperation1 {
    /// Record of the operation
    #[serde(rename = "operation")]
    pub operation: Operation,
    /// Result of the operation
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<bool>,
}

impl SpecsOperation1 {
    /// Record of the operation in progress
    pub fn new(operation: Operation) -> SpecsOperation1 {
        SpecsOperation1 {
            operation,
            result: None,
        }
    }
}

/// Record of the operation
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operation {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Create")]
    Create,
    #[serde(rename = "Destroy")]
    Destroy,
}

