/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SpecsOwners : Owner Resource



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpecsOwners {
    #[serde(rename = "nexuses")]
    pub nexuses: Vec<String>,
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<String>,
}

impl SpecsOwners {
    /// Owner Resource
    pub fn new(nexuses: Vec<String>) -> SpecsOwners {
        SpecsOwners {
            nexuses,
            volume: None,
        }
    }
}


