/*
 * Mayastor RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Specs : Specs detailing the requested configuration of the objects.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Specs {
    /// nexus specs
    #[serde(rename = "nexuses")]
    pub nexuses: Vec<crate::models::SpecsNexuses>,
    /// pool specs
    #[serde(rename = "pools")]
    pub pools: Vec<crate::models::SpecsPools>,
    /// replica specs
    #[serde(rename = "replicas")]
    pub replicas: Vec<crate::models::SpecsReplicas>,
    /// volume specs
    #[serde(rename = "volumes")]
    pub volumes: Vec<crate::models::SpecsVolumes>,
}

impl Specs {
    /// Specs detailing the requested configuration of the objects.
    pub fn new(nexuses: Vec<crate::models::SpecsNexuses>, pools: Vec<crate::models::SpecsPools>, replicas: Vec<crate::models::SpecsReplicas>, volumes: Vec<crate::models::SpecsVolumes>) -> Specs {
        Specs {
            nexuses,
            pools,
            replicas,
            volumes,
        }
    }
}


